Name: 'App name'
Description: >
  This is a potential
  description of the app.
Version: '1.0.0'
ProductNumber: 'abcdefg123456'
Imported: '2000-04-01T06:00:00.000Z'
Frontends:
 - Port: 54180
   Path: null
   Protocol: http
 - Port: 54280
   Path: "/cgi/ui"
Middlelayers:
 - Port: 54179
   Path: null
   Protocol: https
Categories:
 - "Production"
 - "Sensors"